### ISSUE TITLE
[dev.icinga.com #12931] Link is not generated in Comment detail pane

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-generictts#3]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12931

**Created by tobiasvdk on 2016-10-14 18:57:41 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-14 18:57:41 +00:00 (in Redmine)_

---

If you go to the Comment pane (Overview -&gt; Comments -&gt; click on a comment) then the link to the TTS is not generated in Comment detail pane:
![tts_no_link_in_comment.png](https://dev.icinga.com/attachments/download/3695/tts_no_link_in_comment.png)

**Attachments**

* [tts_no_link_in_comment.png](https://dev.icinga.com/attachments/download/3695/tts_no_link_in_comment.png) tobiasvdk - _2016-10-14 18:57:01 +00:00_

**Comment by l13t** [comment]
hi

any updates on this issue?
i'm running jira. i generated regex correctly. but plugin doesn't rewrite comments/ack/downtime messagees for me.
